### ISSUE TITLE
Update or removing the cloned folder break Prep

### ISSUE THREAD

**Issue by Kyrela** [Philippe-cheype/Prep#4]
Due to the fact that the newer versions now requires to keep the original Prep folder, the update, wich removes it, cause Prep to crash after an update.

In my opinion, Prep should not be dependent to other files, or these files should also be installed - but keeping prep as a single file should be more easy and more clean.
To increase readability, comments should suffice.

**Comment by phil-chp** [comment]
I still have to debug one thing, current main is unstable, i will close it before tomorrow

**Comment by Kyrela** [comment]
Any update concerning this issue?

**Comment by phil-chp** [comment]
Outdated, you already updated main enough for it to be stable

Closing
